/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author kelompok 3
 */
public class inputsiswa extends javax.swing.JFrame {

    /**
     * Creates new form inputmhs
     */
    public inputsiswa(){
        initComponents();
        setcombo();
        
        try {
             BufferedImage beam = ImageIO.read(getClass().getResource("library.png"));
             setIconImage(beam); 
        } catch (IOException ex) {
            Logger.getLogger(splashscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.setTitle("Input Data Siswa");
    }
private void setcombo(){
     cmbkelas.setEnabled(false);
    cmbjurusan.addItem("RPL");
    cmbjurusan.addItem("TEI");
    cmbjurusan.addItem("PBS");
    cmbjurusan.addItem("KA");
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblid = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtnis = new javax.swing.JTextField();
        cmbjurusan = new javax.swing.JComboBox<>();
        cmbkelas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtnama = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        lblid.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        txtnis.setText("NIS");
        txtnis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnisMouseClicked(evt);
            }
        });
        txtnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnisActionPerformed(evt);
            }
        });
        txtnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnisKeyReleased(evt);
            }
        });

        cmbjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jurusan" }));
        cmbjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjurusanActionPerformed(evt);
            }
        });

        cmbkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelas" }));
        cmbkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkelasActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtnama.setText("Nama");
        txtnama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnamaMouseClicked(evt);
            }
        });
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("FORM INPUT SISWA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel3)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(cmbkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnisActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtnisActionPerformed

    private void txtnisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnisMouseClicked
txtnis.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnisMouseClicked

    private void cmbjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjurusanActionPerformed

     if(cmbjurusan.getSelectedItem().equals("Jurusan")){
        
         cmbkelas.setSelectedItem("Kelas");
    cmbkelas.setEnabled(false);
     }
        else if(cmbjurusan.getSelectedItem().equals("RPL")){
        cmbkelas.setEnabled(true);
        cmbkelas.removeAllItems();
        cmbkelas.addItem("10 RPL 1");
        cmbkelas.addItem("10 RPL 2");
        cmbkelas.addItem("10 RPL 3");
        cmbkelas.addItem("11 RPL 1");
        cmbkelas.addItem("11 RPL 2");
        cmbkelas.addItem("11 RPL 3");
        cmbkelas.addItem("12 RPL 1");
        cmbkelas.addItem("12 RPL 2");
        cmbkelas.addItem("12 RPL 3");
    }
    else if(cmbjurusan.getSelectedItem().equals("TEI")){
        cmbkelas.setEnabled(true);
        cmbkelas.removeAllItems();
        cmbkelas.addItem("10 TEI 1");
        cmbkelas.addItem("10 TEI 2");
        cmbkelas.addItem("10 TEI 3");
        cmbkelas.addItem("10 TEI 4");
        cmbkelas.addItem("11 TEI 1");
        cmbkelas.addItem("11 TEI 2");
        cmbkelas.addItem("11 TEI 3");
        cmbkelas.addItem("11 TEI 4");
        cmbkelas.addItem("12 TEI 1");
        cmbkelas.addItem("12 TEI 2");
        cmbkelas.addItem("12 TEI 3");
        cmbkelas.addItem("12 TEI 4");
    }
    else if(cmbjurusan.getSelectedItem().equals("PBS")){
        cmbkelas.setEnabled(true);
        cmbkelas.removeAllItems();
        cmbkelas.addItem("10 PBS 1");
        cmbkelas.addItem("10 PBS 2");
        cmbkelas.addItem("11 PBS 1");
        cmbkelas.addItem("11 PBS 2");
        cmbkelas.addItem("12 PBS 1");
        cmbkelas.addItem("12 PBS 2");
    }
    else if(cmbjurusan.getSelectedItem().equals("KA")){
        cmbkelas.setEnabled(true);
        cmbkelas.removeAllItems();
        cmbkelas.addItem("10 KA 1");
        cmbkelas.addItem("10 KA 2");
        cmbkelas.addItem("11 KA 1");
        cmbkelas.addItem("11 KA 2");
        cmbkelas.addItem("12 KA 1");
        cmbkelas.addItem("12 KA 2");
        cmbkelas.addItem("13 KA 1");
        cmbkelas.addItem("13 KA 2");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbjurusanActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nis = txtnis.getText();
    String nama = txtnama.getText();
    if(nis.equals("")||nama.equals("")){
            JOptionPane.showMessageDialog(null,"Isi Semua Form Yang Tersedia ");
        
    }
    else if(cmbjurusan.getSelectedItem().equals("Jurusan")||cmbkelas.getSelectedItem().equals("Kelas")){
            JOptionPane.showMessageDialog(null,"Pilih jurusan atau kelas ");
        }
        else{
        try {
            String sql1 = "INSERT INTO siswa"
                    + " VALUES ('"+txtnis.getText()+"','" + txtnama.getText() + "','" + cmbjurusan.getSelectedItem()
                    + "','" + cmbkelas.getSelectedItem() + "')";
            java.sql.Connection kon = (Connection) koneksi.koneksi();
            java.sql.PreparedStatement pdt = kon.prepareStatement(sql1);
            pdt.execute();
           JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        new datasiswa().setVisible(true);
        dispose();
        } catch (Exception b) {
            JOptionPane.showMessageDialog(this, b.getMessage());
        }   
  
    }
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamaMouseClicked
txtnama.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaMouseClicked

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnisKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnisKeyReleased

    private void cmbkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkelasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new datasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbjurusan;
    private javax.swing.JComboBox<String> cmbkelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnis;
    // End of variables declaration//GEN-END:variables
}
