/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author kelompok 3
 */
public class siswa extends javax.swing.JFrame {

    /**
     * Creates new form siswa
     */
    public siswa(){
        initComponents();
        
        tampil();
        setcombo();
        
        
        try {
           BufferedImage beam = ImageIO.read(getClass().getResource("library.jpg"));
             setIconImage(beam); 
        } catch (IOException ex) {
            Logger.getLogger(splashscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.setTitle("Aplikasi Perpustakaan");
    }
    private void setcombo(){
     
    cmbjurusan.addItem("RPL");
    cmbjurusan.addItem("TEI");
    cmbjurusan.addItem("PBS");
    cmbjurusan.addItem("KA");
    
    
}

   private void tampil(){
          try {
    String ID = session.getid();           
           String sql = "select*from siswa where nis = '"+ID+"'";
             java.sql.Connection conn = (Connection) koneksi.koneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
        
       txtnis.setText(res.getString(1));
        txtnama.setText(res.getString(2));
        cmbjurusan.getModel().setSelectedItem(res.getString(3));
        cmbkelas.getModel().setSelectedItem(res.getString(4));
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnama = new javax.swing.JTextField();
        txtnis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cmbjurusan = new javax.swing.JComboBox<>();
        cmbkelas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnama.setText("Nama");
        txtnama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnamaMouseClicked(evt);
            }
        });
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 500, 40));

        txtnis.setText("NIS");
        txtnis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnisMouseClicked(evt);
            }
        });
        txtnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnisActionPerformed(evt);
            }
        });
        txtnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnisKeyReleased(evt);
            }
        });
        jPanel1.add(txtnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 500, 40));

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kembali1.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        cmbjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jurusan" }));
        cmbjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjurusanActionPerformed(evt);
            }
        });
        jPanel1.add(cmbjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 170, 30));

        cmbkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelas" }));
        jPanel1.add(cmbkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamaMouseClicked
        txtnama.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaMouseClicked

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnisMouseClicked
        txtnis.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnisMouseClicked

    private void txtnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnisActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtnisActionPerformed

    private void txtnisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnisKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnisKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nis = txtnis.getText();
    String nama = txtnama.getText();
      if(nis.equals("")||nama.equals("")){
            JOptionPane.showMessageDialog(null,"Isi Semua Form Yang Tersedia ");
        
    }
    else if(cmbjurusan.getSelectedItem().equals("Jurusan")||cmbkelas.getSelectedItem().equals("Kelas")){
            JOptionPane.showMessageDialog(null,"Pilih jurusan atau kelas ");
        }
        else{
        try {
            String query ="UPDATE siswa SET nis = '"+txtnis.getText()
                    +"',nama = '"+txtnama.getText()
                    +"', jurusan = '"+cmbjurusan.getSelectedItem()
                    +"',kelas = '"+cmbkelas.getSelectedItem()
                    +"' WHERE nis = '"+txtnis.getText()+"'";
            java.sql.Connection kon=(Connection)koneksi.koneksi();
            java.sql.PreparedStatement pdt=kon.prepareStatement(query);
            pdt.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        new datasiswa().setVisible(true);
dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new datasiswa().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
            String sql ="delete from siswa where nis='"+txtnis.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.koneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
new datasiswa().setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjurusanActionPerformed
if(cmbjurusan.getSelectedItem().equals("Jurusan")){

            cmbkelas.setSelectedItem("Kelas");
            cmbkelas.setEditable(false);
        }
        else if(cmbjurusan.getSelectedItem().equals("RPL")){
            cmbkelas.setEditable(true);
            cmbkelas.removeAllItems();
            cmbkelas.addItem("10 RPL 1");
            cmbkelas.addItem("10 RPL 2");
            cmbkelas.addItem("10 RPL 3");
            cmbkelas.addItem("11 RPL 1");
            cmbkelas.addItem("11 RPL 2");
            cmbkelas.addItem("11 RPL 3");
            cmbkelas.addItem("12 RPL 1");
            cmbkelas.addItem("12 RPL 2");
            cmbkelas.addItem("12 RPL 3");
        }
        else if(cmbjurusan.getSelectedItem().equals("TEI")){
            cmbkelas.setEditable(true);
            cmbkelas.removeAllItems();
            cmbkelas.addItem("10 TEI 1");
            cmbkelas.addItem("10 TEI 2");
            cmbkelas.addItem("10 TEI 3");
            cmbkelas.addItem("10 TEI 4");
            cmbkelas.addItem("11 TEI 1");
            cmbkelas.addItem("11 TEI 2");
            cmbkelas.addItem("11 TEI 3");
            cmbkelas.addItem("11 TEI 4");
            cmbkelas.addItem("12 TEI 1");
            cmbkelas.addItem("12 TEI 2");
            cmbkelas.addItem("12 TEI 3");
            cmbkelas.addItem("12 TEI 4");
        }
        else if(cmbjurusan.getSelectedItem().equals("PBS")){
            cmbkelas.setEditable(true);
            cmbkelas.removeAllItems();
            cmbkelas.addItem("10 PBS 1");
            cmbkelas.addItem("10 PBS 2");
            cmbkelas.addItem("11 PBS 1");
            cmbkelas.addItem("11 PBS 2");
            cmbkelas.addItem("12 PBS 1");
            cmbkelas.addItem("12 PBS 2");
        }
        else if(cmbjurusan.getSelectedItem().equals("KA")){
            cmbkelas.setEditable(true);
            cmbkelas.removeAllItems();
            cmbkelas.addItem("10 KA 1");
            cmbkelas.addItem("10 KA 2");
            cmbkelas.addItem("11 KA 1");
            cmbkelas.addItem("11 KA 2");
            cmbkelas.addItem("12 KA 1");
            cmbkelas.addItem("12 KA 2");
            cmbkelas.addItem("13 KA 1");
            cmbkelas.addItem("13 KA 2");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbjurusanActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbjurusan;
    private javax.swing.JComboBox<String> cmbkelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnis;
    // End of variables declaration//GEN-END:variables
}
